### ISSUE TITLE
How to specify -x with a new technology

### ISSUE THREAD

**Issue by ogandril** [pachterlab/kallistobustools#14]
Me again :-)
I looked into finer details on how to specify the -x argument.
From the manuel "The first part bc is 0,0,16 indicating it is in the 0-th file, the barcode starts at the 0-th bp and ends at the 16-th bp in the sequence (i.e. 16bp barcode), " 
But if you start at the position 0, and the barcode is 16 bp, why not write 0,0,15?
Similarly, "the UMI is similarly in the same file, right after the barcode in position 16-26" 
So if it is after the barcode, why not write 0,17,26 ? (16,26 would be a 11 bp UMI, no?)

Olivier

**Comment by mschilli87** [comment]
What exactly is your question? To me it seams you read and understood the documentation.
A 16 bp barcode at the very 5' end of the first file could have been endoded as `0,0,15`, `1,1,16` (or in many other ways) but was was chosen to be `0,0,15`. Does is matter why? It is a common scheme in programming to have zero-based half-opened intervals. I guess mainly because it allows looping with `for(i = 0; i < len(a); ++i){ /* Do sth. w/ a[i]. */ }`.
To put it in mathematical terms (I do not know your background): For integers(!) [0, 16) = [0, 15] (length: 16) and [16, 26) = [16, 25] (length: 10).

Let's consider an example:

```
Pos. DIV 10:   00000000001111111111222222222...
Pos. MOD 10:   01234567890123456789012345678...
Read sequence: BBBBBBBBBBBBBBBBUUUUUUUUUUNNN...
```

Where `B` means barcode, `U` UMI, and `N` the rest of the read.
We can transpose this to make the position within the read more human readable

```
00 B <- Begin barcode interval (closed)
01 B
02 B
03 B
04 B
05 B
06 B
07 B
08 B
09 B
10 B
11 B
12 B
13 B
14 B
15 B <- End barcode interval (closed)
16 U <- Begin UMI interval (closed) / End barcode interval (open)
17 U
18 U
19 U
20 U
21 U
22 U
23 U
24 U
25 U <- End UMI interval (closed)
26 N <- End UMI interval (open)
27 N
28 N
.. .
.. .
.. .
```

Whatever your setup is, draw this kind of numbered version (make sure to start with zero, not one) and remeber that the intervals you need to specify are closed on the left (*i.e.* the first interval boundary is the first position included in the interval) but open on the right (*i.e.* the second interval boundary is the first position that is *not* included in the interval anymore).

You might not like this scheme, but it is clear, unambiguous, and documented (as cited by you).
And while it could have been done different (with other drawbacks), changing it now would break existing code of everyone that used the `-x` flag so far. Thus (I hope) that's off the table.

So again, not really sure what you are/were aiming for with this issue...

**Comment by ogandril** [comment]
Thank's a lot for your fast answer!!!
I just wanted to make sure I was making not mistake, not for you to change the code!
But your sentence: "the intervals you need to specify are closed on the left but open on the right" makes things cristal clear.
