### ISSUE TITLE
Splitting multimapping read with EM algorithm

### ISSUE THREAD

**Issue by joycekang** [pachterlab/kallistobustools#28]
Hi kallisto | bustools team,

Thanks for developing such a great pipeline!
I was wondering, does the current version of `kb count` handle multimapping reads? According to the [bustools release 0.39.4](https://github.com/BUStools/bustools/releases/tag/v0.39.4), it seems like bustools can split multimapped reads using the EM algorithm, but the kallisto|bustools tutorial does not seem to discuss this issue. If I want to use the EM option, would I need to run `kallisto` (with the single-cell options) and `bustools count` separately, rather than use `kb count`?

Thanks so much in advance!

```
The bustools count command adds the --em option that estimates gene abundances using an EM algorithm for reads that pseudoalign to multiple genes.

Note that the --multimapping option splits the read counts evenly across all genes, whereas the EM algorithm gives a more statistically valid answer. The two options are mutually exclusive.
```

**Comment by Yenaled** [comment]
Hi Joyce! Thanks for using our pipeline! kb count currently does not support the EM algorithm for multimapping reads; it does support a simpler multimapping algorithm (via --mm) that simply divides counts equally among multimappers.

For use of the EM algorithm, please use kallisto and bustools rather than the kb wrapper for now. kb doesn't support all the features that bustools currently has, but it is our goal to add them to kb as soon as we can!

Best,
Delaney

**Comment by joycekang** [comment]
Great to know - thanks!
